INSERT INTO earlybird_genres (genre)
VALUES 
  ('Action & Adventure'), 
  ('Art & Photography'), 
  ('Biography'),
  ('Children''s'),
  ('Contemporary Fiction'),
  ('Dystopian'),
  ('Essay'),
  ('Fantasy'),
  ('Food & Drink'),
  ('Comic / Graphic Novel'),
  ('Guide / How-to'),
  ('Historial Ficiton'),
  ('History'),
  ('Horror'),
  ('Humanities & Social Sciences'),
  ('Literary Fiction'),
  ('LGBTQ+'),
  ('Memoir & Autobiography'),
  ('Mystery'),
  ('Parenting & Families'),
  ('Poetry'),
  ('Psychological Fiction'),
  ('Religion & Spirituality'),
  ('Romance'),
  ('Science Fiction (Sci-Fi)'),
  ('Science & Technology'),
  ('Self-help'),
  ('Short Stories'),
  ('Women''s Fiction'),
  ('Textbook'),
  ('Thriller & Suspense'),
  ('Travel'),
  ('True Crime');